Repository Schrolli91/BOSWatch, pull requests merged in 2018-10, with the labels that each got.

#378 Pushover: Sep. Prio for RIC and ZVEI
  CHANGELOG.md
  config/config.template.ini
  plugins/Pushover/Pushover.py
Labels: Review needed

#380 Update Telegram.py
  CHANGELOG.md
  plugins/Telegram/Telegram.py
Labels: Plugin, Review needed

#381 prepare for version 2.4.1
  CHANGELOG.md
  README.md
  boswatch.py
  config/config.template.ini
  includes/NMAHandler.py
  includes/globalVars.py
  includes/pynma/README.md
  includes/pynma/__init__.py
  includes/pynma/pynma.py
  plugins/Pushover/Pushover.py
  plugins/Telegram/Telegram.py
  plugins/notifyMyAndroid/notifyMyAndroid.py
Labels: In Progress
