Repository Schrolli91/BOSWatch, pull requests merged in 2019-10, with the labels that each got.

#414 HOTFIX pocsag decoder
  includes/decoders/poc.py
Labels: BOSWatch, Bug, Priorität Hoch

#418 Sound-Settings für Pushover
  CHANGELOG.md
  config/config.template.ini
  plugins/Pushover/Pushover.py
Labels: Plugin

#416 Refactoring RegEx
  CHANGELOG.md
  includes/descriptionList.py
Labels: BOSWatch, Bug, Review needed
